import type { KpiKey } from '../types'
import type { JpxIndustry } from './industryKpiPolicy'

export type GoldenRiskFlag =
  | 'baseline-industry-coverage'
  | 'bank-policy'
  | 'securities-policy'
  | 'insurance-policy'
  | 'other-financial-policy'
  | 'real-estate-inventory'
  | 'stale-roe-scale'
  | 'low-roe-not-zero'
  | 'loss-making'
  | 'large-cap-cross-check'
  | 'capital-intensive'
  | 'transport-cyclical'
  | 'regulated-utility'

export interface GoldenIndustryCase {
  code: string
  companyName: string
  industry: JpxIndustry
  reason: string
  riskFlags: readonly GoldenRiskFlag[]
  minimumKpis: readonly KpiKey[]
}

const commonOperatingKpis = [
  'revenueGrowth',
  'operatingMargin',
  'netMargin',
  'roe',
  'equityRatio',
] as const satisfies readonly KpiKey[]

const financialKpis = ['roe', 'per', 'pbr'] as const satisfies readonly KpiKey[]

export const goldenIndustryCases = [
  {
    code: '1301',
    companyName: '極洋',
    industry: '水産・農林業',
    reason: '33業種の基礎カバレッジ。水産在庫を持つため棚卸資産KPIも監視対象にする',
    riskFlags: ['baseline-industry-coverage'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '1605',
    companyName: 'INPEX',
    industry: '鉱業',
    reason: '資源価格と大型投資の影響が大きい資本集約型企業',
    riskFlags: ['baseline-industry-coverage', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '1802',
    companyName: '大林組',
    industry: '建設業',
    reason: '工事進行・売掛・棚卸の変動が大きく、運転資本KPIの回帰確認に使う',
    riskFlags: ['baseline-industry-coverage'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '2206',
    companyName: '江崎グリコ',
    industry: '食料品',
    reason: '食品メーカーの標準ケース。売上・利益率・在庫の基本抽出を確認する',
    riskFlags: ['baseline-industry-coverage'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '3402',
    companyName: '東レ',
    industry: '繊維製品',
    reason: '素材系製造業として在庫・営業CF・負債の整合を確認する',
    riskFlags: ['baseline-industry-coverage', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '3861',
    companyName: '王子ホールディングス',
    industry: 'パルプ・紙',
    reason: '設備産業で負債・減価償却影響が大きく、一般事業会社KPIの基準ケースにする',
    riskFlags: ['baseline-industry-coverage', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '4005',
    companyName: '住友化学',
    industry: '化学',
    reason: '景気循環・赤字転落が起きやすく、利益率・ROEの下振れケースを固定する',
    riskFlags: ['baseline-industry-coverage', 'loss-making'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '4502',
    companyName: '武田薬品工業',
    industry: '医薬品',
    reason: '大型買収・無形資産の影響が大きく、ROEと利益率の継続確認に使う',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5020',
    companyName: 'ENEOSホールディングス',
    industry: '石油・石炭製品',
    reason: '資源価格と棚卸評価の影響が大きい業種カバレッジケース',
    riskFlags: ['baseline-industry-coverage', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5108',
    companyName: 'ブリヂストン',
    industry: 'ゴム製品',
    reason: 'グローバル製造業として売上・利益率・在庫KPIを確認する',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5201',
    companyName: 'AGC',
    industry: 'ガラス・土石製品',
    reason: '設備投資と市況影響が大きい素材企業の基準ケース',
    riskFlags: ['baseline-industry-coverage', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5401',
    companyName: '日本製鉄',
    industry: '鉄鋼',
    reason: '市況産業かつ財務レバレッジ確認に重要な大型ケース',
    riskFlags: ['baseline-industry-coverage', 'capital-intensive', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5713',
    companyName: '住友金属鉱山',
    industry: '非鉄金属',
    reason: '資源価格連動と持分法影響を含む非鉄の代表ケース',
    riskFlags: ['baseline-industry-coverage', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5938',
    companyName: 'LIXIL',
    industry: '金属製品',
    reason: '住宅設備系で在庫・利益率の変動を確認する',
    riskFlags: ['baseline-industry-coverage'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '6301',
    companyName: '小松製作所',
    industry: '機械',
    reason: '機械セクターの大型代表。売上成長・利益率・在庫の標準確認に使う',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '6501',
    companyName: '日立製作所',
    industry: '電気機器',
    reason: '大型コングロマリットで、セグメント値ではなく全社値を取れるか確認する',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '7203',
    companyName: 'トヨタ自動車',
    industry: '輸送用機器',
    reason: '金融子会社を含む大型製造業として、一般KPIの過剰警告を監視する',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '7733',
    companyName: 'オリンパス',
    industry: '精密機器',
    reason: '精密機器の代表。利益率とROEの継続取得を確認する',
    riskFlags: ['baseline-industry-coverage'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '7974',
    companyName: '任天堂',
    industry: 'その他製品',
    reason: '高利益率・高キャッシュ企業として、スコア上限側の挙動を確認する',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '9501',
    companyName: '東京電力ホールディングス',
    industry: '電気・ガス業',
    reason: '規制産業で負債・利益率が特殊になりやすい監視ケース',
    riskFlags: ['baseline-industry-coverage', 'regulated-utility'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '9020',
    companyName: '東日本旅客鉄道',
    industry: '陸運業',
    reason: '固定資産と有利子負債が大きい交通インフラケース',
    riskFlags: ['baseline-industry-coverage', 'transport-cyclical', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '9101',
    companyName: '日本郵船',
    industry: '海運業',
    reason: '市況変動が激しく、ROE・利益率の極端値確認に使う',
    riskFlags: ['baseline-industry-coverage', 'transport-cyclical'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '9201',
    companyName: '日本航空',
    industry: '空運業',
    reason: 'コロナ後の回復や燃料費影響が大きい景気循環ケース',
    riskFlags: ['baseline-industry-coverage', 'transport-cyclical'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '9301',
    companyName: '三菱倉庫',
    industry: '倉庫・運輸関連業',
    reason: '物流・不動産を併せ持つため、一般KPIと資産型ビジネスの境界を確認する',
    riskFlags: ['baseline-industry-coverage'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '9432',
    companyName: '日本電信電話',
    industry: '情報・通信業',
    reason: '通信大型株として、安定収益・負債・PER/PBRの標準確認に使う',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '8058',
    companyName: '三菱商事',
    industry: '卸売業',
    reason: '商社は売上・利益率の解釈が難しく、共通評価の監視対象にする',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '8267',
    companyName: 'イオン',
    industry: '小売業',
    reason: '小売・金融子会社・在庫を含む大型複合ケース',
    riskFlags: ['baseline-industry-coverage'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '8306',
    companyName: '三菱UFJフィナンシャル・グループ',
    industry: '銀行業',
    reason: '銀行業の負債・営業CF・運転資本KPI除外を固定する',
    riskFlags: ['baseline-industry-coverage', 'bank-policy', 'large-cap-cross-check'],
    minimumKpis: financialKpis,
  },
  {
    code: '8604',
    companyName: '野村ホールディングス',
    industry: '証券、商品先物取引業',
    reason: '証券業の金融KPI限定ルールを固定する',
    riskFlags: ['baseline-industry-coverage', 'securities-policy'],
    minimumKpis: financialKpis,
  },
  {
    code: '8750',
    companyName: '第一生命ホールディングス',
    industry: '保険業',
    reason: '保険業の金融KPI限定ルールを固定する',
    riskFlags: ['baseline-industry-coverage', 'insurance-policy'],
    minimumKpis: financialKpis,
  },
  {
    code: '8591',
    companyName: 'オリックス',
    industry: 'その他金融業',
    reason: 'その他金融業で負債・ネットキャッシュを一般企業扱いしないための代表ケース',
    riskFlags: ['baseline-industry-coverage', 'other-financial-policy'],
    minimumKpis: ['revenueGrowth', 'netMargin', 'roe', 'per', 'pbr'],
  },
  {
    code: '8801',
    companyName: '三井不動産',
    industry: '不動産業',
    reason: '在庫・有利子負債が大きい不動産業の大型基準ケース',
    riskFlags: ['baseline-industry-coverage', 'real-estate-inventory', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '6098',
    companyName: 'リクルートホールディングス',
    industry: 'サービス業',
    reason: 'サービス業の大型標準ケース。高利益率・無形寄りビジネスの確認に使う',
    riskFlags: ['baseline-industry-coverage', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '146A',
    companyName: 'コロンビア・ワークス',
    industry: '不動産業',
    reason: 'ROE前年差・EDINET/TDnet差異・不動産在庫の過去不具合を固定する',
    riskFlags: ['real-estate-inventory'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5987',
    companyName: 'オーネックス',
    industry: '金属製品',
    reason: '旧ROEスケール問題で0表示化した銘柄。低ROEを0バグと混同しないため固定する',
    riskFlags: ['stale-roe-scale', 'low-roe-not-zero'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '5988',
    companyName: 'パイオラックス',
    industry: '金属製品',
    reason: '旧ROEスケール問題で極小値化した銘柄。マイナス低ROEの表示を監視する',
    riskFlags: ['stale-roe-scale', 'low-roe-not-zero'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '7083',
    companyName: 'AHCグループ',
    industry: 'サービス業',
    reason: '旧ROEスケール問題で0近辺になった小型サービス業ケース',
    riskFlags: ['stale-roe-scale', 'low-roe-not-zero'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '8217',
    companyName: 'オークワ',
    industry: '小売業',
    reason: '旧モデルROEが隔離された小売ケース。未取得と誤値表示の境界を確認する',
    riskFlags: ['stale-roe-scale'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '8411',
    companyName: 'みずほフィナンシャルグループ',
    industry: '銀行業',
    reason: '銀行業ポリシーの2社目。業種ルールが1社依存にならないようにする',
    riskFlags: ['bank-policy', 'large-cap-cross-check'],
    minimumKpis: financialKpis,
  },
  {
    code: '8766',
    companyName: '東京海上ホールディングス',
    industry: '保険業',
    reason: '保険業ポリシーの2社目。保険負債を一般負債評価しないことを固定する',
    riskFlags: ['insurance-policy', 'large-cap-cross-check'],
    minimumKpis: financialKpis,
  },
  {
    code: '8697',
    companyName: '日本取引所グループ',
    industry: 'その他金融業',
    reason: 'その他金融の追加ケース。市場インフラ型金融として一般負債評価を避ける',
    riskFlags: ['other-financial-policy'],
    minimumKpis: ['revenueGrowth', 'netMargin', 'roe', 'per', 'pbr'],
  },
  {
    code: '8601',
    companyName: '大和証券グループ本社',
    industry: '証券、商品先物取引業',
    reason: '証券業ポリシーの2社目。顧客資産・市場評価影響を一般KPIから外す',
    riskFlags: ['securities-policy'],
    minimumKpis: financialKpis,
  },
  {
    code: '3289',
    companyName: '東急不動産ホールディングス',
    industry: '不動産業',
    reason: '不動産の追加ケース。有利子負債と販売用不動産をセットで確認する',
    riskFlags: ['real-estate-inventory', 'capital-intensive'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '9984',
    companyName: 'ソフトバンクグループ',
    industry: '情報・通信業',
    reason: '投資会社的性格を持つ大型特殊ケース。一般KPIの過剰解釈を監視する',
    riskFlags: ['large-cap-cross-check', 'loss-making'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '6758',
    companyName: 'ソニーグループ',
    industry: '電気機器',
    reason: '金融・ゲーム・半導体を含む複合大型企業として全社値選択を確認する',
    riskFlags: ['large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '7201',
    companyName: '日産自動車',
    industry: '輸送用機器',
    reason: '自動車の低収益・金融子会社影響ケース。トヨタだけに依存しない',
    riskFlags: ['transport-cyclical', 'loss-making'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '4661',
    companyName: 'オリエンタルランド',
    industry: 'サービス業',
    reason: '高固定費・高収益サービス業の追加ケース。営業CFと利益率の整合を見る',
    riskFlags: ['large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
  {
    code: '7011',
    companyName: '三菱重工業',
    industry: '機械',
    reason: '防衛・重工の大型案件型企業。売掛・棚卸・受注影響を監視する',
    riskFlags: ['capital-intensive', 'large-cap-cross-check'],
    minimumKpis: commonOperatingKpis,
  },
] as const satisfies readonly GoldenIndustryCase[]

export const goldenIndustryCount = goldenIndustryCases.length
